### PR TITLE
feat: add tsup and swc template options

### PR DESCRIPTION
**Pull request by MajesticString**

### CODE REVIEW

**Comment by enxg** [comment]
CLI clones the sapphiredev/examples repo for the project templates, you need to open an issue on that repo.

https://github.com/sapphiredev/examples

**Review by enxg — APPROVED** [review]

**Comment by MajesticString** [comment]
Already added those templates there :)

**Comment by enxg** [comment]
> Already added those templates there :)

👍

**Comment by enxg** [comment]
@all-contributors please add @MajesticString for code

**Pull request merged**
